### ISSUE TITLE
Documentation: Add section in README to define the scope of this repo better

### ISSUE THREAD

**Issue by dsotirakis** [grafana/shared-workflows#74]
Recently we're getting PRs and be mentioned in discussions about what this repository should contain. It's name indicates a repository which should have _any kind_ of shared workflows which can used for more than one cases. This is not quite true since up until now we are keeping it down to have only workflows which are not specific to any case (like Grafana only for example) and can be used by **all** repositories (auth, pull and push from and to Docker registries, lint PRs etc)

**Comment by ricky-undeadcoders** [comment]
I have a PR open for this: https://github.com/grafana/shared-workflows/pull/77

It appears that we have the branch protection rules setup so that we require reviews from the code owners, so as long as CODEOWNERS is maintained then this should be a valid approach.

It's probably worth adding a test for `grafana/shared-workflows` to verify that each file has an entry in CODEOWNERS.

**Comment by zerok** [comment]
For the CODEOWNERS check, there already is a workflow used in grafana/grafana et al. that we could copy over. That probably only makes sense, though, if we remove the fallback rule `* @grafana/platform-productivity`.

**Comment by ricky-undeadcoders** [comment]
PR for this: https://github.com/grafana/shared-workflows/pull/121
